# Generated by Django 5.2 on 2025-04-24 06:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Node',
            fields=[
                ('device_id', models.AutoField(primary_key=True, serialize=False)),
                ('display_name', models.CharField(max_length=100)),
                ('location_name', models.CharField(max_length=100)),
                ('ip_address', models.GenericIPAddressField(validators=[django.core.validators.validate_ipv46_address])),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('maintenance', 'Maintenance')], default='inactive', max_length=20)),
                ('last_seen', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
